### ISSUE TITLE
Origin header required

### ISSUE THREAD

**Issue by qrush** [pgriess/node-websocket-client#2]
Wasn't specified, so I added it. Was breaking http://socket.io when trying to connect.

Spec reference: http://en.wikipedia.org/wiki/WebSockets

Patch: http://github.com/qrush/node-websocket-client/commit/5c770af101e324b9acf41896354c404e408c5ac3

**Comment by pgriess** [comment]
Add 'opts' param to WebSocket(); set Origin hdr.

Closed by 9908f3f1b0d284ce0ae2cdd799bd895182f6c878
- Fix inspired by nick@quaran.to.
