### ISSUE TITLE
Client should detect closing frame and close the connection (not crash)

### ISSUE THREAD

**Issue by izuzak** [pgriess/node-websocket-client#4]
As per http://tools.ietf.org/html/draft-hixie-thewebsocketprotocol-76, the client should detect the closing frame sequence of bytes, 0xFF followed by 0x00, and close the connection.

Currently however, the client crashes when receiving the closing frame with the error "High-byte frames not yet supported". Tested with https://github.com/miksago/node-websocket-server.

**Comment by networkimprov** [comment]
Fixed here:
https://github.com/networkimprov/websocket.MQ/commit/a6a01c61c7f57760ce2a2c6484cb0d5e5b13e358

**Comment by izuzak** [comment]
nice, thanks!

**Comment by networkimprov** [comment]
More fixes posted...

https://github.com/networkimprov/websocket.MQ/blob/master/websocket-client/index.js

**Comment by pgriess** [comment]
Thanks.

As it turns out, I implemented a different solution to this a few days back.

**Comment by pgriess** [comment]
@networkimprov, I'll take a look at the rest of your error-handling changes later today. If you want to send me a patch or a pull request, I'd be happy to incorporate some of your fixes.

**Comment by networkimprov** [comment]
What I'd suggest, and I realize it's kindof a project, is using Micheil's websocket-server connection.js module (and possibly others) as a basis for a client. That way you won't be duplicating efforts, and his code has a pretty broad proving ground.
