### ISSUE TITLE
npm install websocket-client fails

### ISSUE THREAD

**Issue by tehnorm** [pgriess/node-websocket-client#7]
$ npm install websocket-client                                             

npm info it worked if it ends with ok
npm info using npm@0.2.19
npm info using node@v0.4.2
npm info fetch http://registry.npmjs.org/websocket-client/-/websocket-client-1.0.0.tgz
npm info calculating sha1 /tmp/npm-1299525208549/1299525208549-0.2477872739546001/tmp.tgz
npm info shasum f8727a2756b2324d1fd1b71e4db4c98a77007cda
npm ERR! Failed unpacking the tarball.
npm ERR! This is very rare. Perhaps the 'gzip' or 'tar' configs
npm ERR! are set improperly?
npm ERR!
npm ERR! couldn't unpack /tmp/npm-1299525208549/1299525208549-0.2477872739546001/tmp.tgz to /tmp/npm-1299525208549/1299525208549-0.2477872739546001/contents
npm ERR! Error installing websocket-client@1.0.0
npm ERR! Error: Failed tar "-vxpf" "-" "-C" "/tmp/npm-1299525208549/1299525208549-0.2477872739546001/contents"
npm ERR! exited with 2
npm ERR!     at ChildProcess.<anonymous> (/usr/local/lib/node/.npm/npm/0.2.19/package/lib/utils/exec.js:48:8)
npm ERR!     at ChildProcess.emit (events.js:45:17)
npm ERR!     at ChildProcess.onexit (child_process.js:171:12)
npm ERR! Report this _entire_ log at http://github.com/isaacs/npm/issues
npm ERR! or email it to npm-@googlegroups.com
npm ERR! Just tweeting a tiny part of the error will not be helpful.
npm not ok

**Comment by pgriess** [comment]
This looks like an npm issue.
